### PR TITLE
use py.test for python tests

### PR DESCRIPTION
**Pull request by jendrikseipp**
I have taken the time to convert our tests for the py.test (https://pytest.org) framework. This has many benefits:

* When running the tests we can now immediately see in the terminal what goes wrong
* Better highlighting of the test results
* Less output if all tests pass (currently one dot is printed for each test module, for new test modules we can change that to being one dot for each test in the test module)
* We benefit from a mature testing framework which will allow us to write real unit tests for the first time (instead of whole txt2tags runs) 
* The hacks in the tests are gone
* Less code

Due to the way in which py.test finds the test cases, I had to change the names of the test modules from xxx/run.py to xxx/test_run.py. You can invoke the tests by going into the test directory and calling "py.test-2.7".

The work on revamping the test suite is not yet done. At the top of lib.py I have noted some open TODOs that can be worked on once this is merged.

Are there any objections to merging this?

### CODE REVIEW

**Comment by fgallaire** [comment]
@jendrikseipp please, revert this right now.
You want stability but you change the tools of the devs without their advice.
As I'm the only one to have done new tests for txt2tags this last years, I have no time to loose to learn something new, as the Aurelio way of test was right until now for txt2tags and still is.

**Comment by jendrikseipp** [comment]
Sorry, I thought there were no objections to merging this.

Apart from the various advantages that this change gives us (see above), nothing much changes for the test suite. You can still define tests in the same way as before.

**Comment by aureliojargas** [comment]
I think evolving the test suite to something more "standard" in the Python community is a great goal, and could improve contributions, since today one has to learn how to create tests in the "txt2tags way".

**Comment by farvardin** [comment]
> @jendrikseipp please, revert this right now.

btw @fgallaire have you reverted the syntax additions you've added without notice recently?

**Comment by fgallaire** [comment]
@farvardin I don't think this additions block others devs in their work.

**Comment by fgallaire** [comment]
@jendrikseipp I just can't run the tests, as I'm the only person to try to fix bugs in txt2tags it's quite a problem. You could reapply this patch after the release, are just before, but now it's blocking for me.

**Comment by jendrikseipp** [comment]
Can you be more explicit, please? What exactly are you trying and what doesn't work?

**Comment by fgallaire** [comment]
@jendrikseipp Please I want to fix txt2tags, not the test suite ! It was a bash syntax error, for some reason I don't understand it now works fine. But I'm lost in the failed test indications. In respect for the work done before, let the only dev work comfortably until the release, py.test is probably great but is obviously not the top txt2tags priority.

**Comment by jendrikseipp** [comment]
If you send me the part of the output you don't understand, I can explain it to you. I would recommend testing one failing module at a time, then the output might be easier to read: `py.test-2.7 -k csv`

The output of this call can be read as follows:

```
...
outfile = '.../txt2tags/test/csv/error.out', okfile = '.../txt2tags/test/csv/ok/error.out'

    def _diff(outfile, okfile):
        out = read_file(outfile)
        out = remove_version(out)
        expected = read_file(okfile)
        expected = remove_version(expected)
>       assert out == expected
E       assert '\nLine 1.\n\...\nLine 2.\n\n' == 'txt2tags: Err...side string\n'
E         + txt2tags: Error: CSV: file error.csv: newline inside string
E         - 
E         - Line 1.
E         - 
E         -   | foo
E         - 
E         - Line 2.
E         -

...
```
The current implementation accepts the input and produces some lines (`out`), while originally we expected the call to fail with an error message (`expected`). The call that failed is always the last captured stdout call. It tells you for which file the test failed. If you want to create your own diff, you can see which files were compared by inspecting the files `outfile` and `okfile`. I just pushed a commit that makes sure that files for which tests failed, are not deleted.

**Comment by fgallaire** [comment]
What is hard to understand in "please let me to finish a 7 years work in a way it's easy for me to catch bugs and fix them" and apply your change on the tests suite after ??

**Pull request merged**
