### PR TITLE
Proposal for txt2tags 3.0, started porting txt2tags to Python 3.7

### PR DESCRIPTION
**Pull request by phorward**
Hello, I've started to port the current txt2tags master to Python 3.7. This version already runs very well with some tests and the documents I've been working on. Please feel free to integrate my modifications or help to continue developing txt2tags. Its still my favorite markup language of choice, have written much documentation and even books with it.

Performed steps:
- Ran 2to3 on all related files
- Removed any unnecessary uncode/utf-8 related handling from txt2tags and txt2tagslite
- Rewrote imports in targets and test, `python3 run.py` in test runs, but not all tests succeed
- Updated version numbering to 3.0

What still has to be done:
- Remove all unicode/utf-8 related code
- Remove obsolete things & code
- Fix tests
- I'm still unaware why there is a txt2tagslite, with redundant code base?!

### CODE REVIEW

**Comment by farvardin** [comment]
Well done!
We should merge your pull request asap (i cant now from my phone because of the travis error)

**Comment by phorward** [comment]
Thanks @farvardin, I hope my changes are okay and work for you.

I really want to keep txt2tags alive, it would be a loss of a very great idea and useful software in case it is discontinued. Bringing it to this state kept just a few hours for me. I'm not familiar with its internals, one of you should look on it and improve, I would assist where I can.

**Comment by farvardin** [comment]
I've reviewed your port, it looks very good, I've converted a few documents I have and most of them are working great. Thank you for this big work!

However, there are still a few differences in some occasion, I'd like to understand what's going on for some errors. For example, in http/error, relative-path.html is not very engaging, some parts are surrounded by b' \n' (like: b'\n').
In some .tex documents, \ (antislash) is replaced by "$\backslash$"

IMHO, before releasing, and during the test phase, the my_version = '3.0' should be kept to my_version = '2.6', because having 3.0 raises some false errors during the test.

Also, the shebang should mention #!/usr/bin/env python3 instead of python (and the current 2.6 version should mention #!/usr/bin/env python2 to avoid runtime errors).

Before merging, I'd like we discuss this with Aurelio and other developpers.

There should be a 2.7 version (at least 2.7-dev) released before jumping to the python 3, and txt2tags 3.0 version.

**Comment by phorward** [comment]
Hello @farvardin,
thank you for a first review and comment. I'm glad that development with txt2tags is still ongoing.

> However, there are still a few differences in some occasion, I'd like to understand what's going on for some errors. For example, in http/error, relative-path.html is not very engaging, some parts are surrounded by b' \n' (like: b'\n').
> In some .tex documents, \ (antislash) is replaced by "$\backslash$"

These are bugs that must be fixed. I'll do that asap when I have some time.

> IMHO, before releasing, and during the test phase, the my_version = '3.0' should be kept to my_version = '2.6', because having 3.0 raises some false errors during the test.

OK. Its on yours how you handle the versioning scheme with txt2tags. I just thought its a new version with a big change, so it might be a major release.
 
> Also, the shebang should mention #!/usr/bin/env python3 instead of python (and the current 2.6 version should mention #!/usr/bin/env python2 to avoid runtime errors).

Of course, I'll fix that in this branch asap.

> There should be a 2.7 version (at least 2.7-dev) released before jumping to the python 3, and txt2tags 3.0 version.

I'm using the current txt2tags development version since a few years now (I've created the package (txt2tags-git in Arch Linux AUR)[https://aur.archlinux.org/packages/txt2tags-git]), especially because it implements a support to export into Markdown which I used a while ago.

It would really be nice to bring the 2.7 version also into an "official" state. For me, it runs very well, but sure not all tests are fine. I'm of the opinion, that its sometimes better to release a good piece of software with some "unfinished perfections" still open, instead of not releasing it at all. I know this perfection thing also, but it often never comes to an end. But... it's on yours!

**Comment by fgallaire** [comment]
Hello @phorward,
first thanks for your interest in txt2tags
second thanks for hacking (so few contributors)
third this branch will not be merged as it.

You change the file for the quite stable not released Python 2 txt2tags 2.7, it's not the way to go.

Feel free to develop in a new txt2tags3 file (or even a new name we could talk about it) in Python 3 (it's probably the way to go).

**Comment by fgallaire** [comment]
@phorward 
txt2tagslite is my work to make txt2tags hackable again what it wasn't anymore due to 11k LOC in one single file.
txt2tagslite has (only) 6k LOC with a modular and simple extension architecture.

I think that for your new txt2tags3 file, you should choose txt2tagslite as basis (and not txt2tags).

**Comment by farvardin** [comment]
> OK. Its on yours how you handle the versioning scheme with txt2tags. I just thought its a new version with a big change, so it might be a major release.

Sure, it should be labelled txt2tags 3.0, but at the moment it's just for avoiding unecessary test errors.
 
> It would really be nice to bring the 2.7 version also into an "official" state. For me, it runs very well, but sure not all tests are fine. I'm of the opinion, that its sometimes better to release a good piece of software with some "unfinished perfections" still open, instead of not releasing it at all. I know this perfection thing also, but it often never comes to an end. But... it's on yours!

I agree, "release early, release often"!

**Comment by phorward** [comment]
Well well, I think I'll rename txt2tagslite in my repo to txt2tags3 (or so) according to @fgallaire's recommendations, and reset the py2 implementation.
When a txt2tags v3 is really wanted, I need more help & assistance especially with the targets. Would it be better in this case to remove some targets first and add them later, so a smaller array of targets must be archived and tested. I'm not familiar with all targets, what I mostly use is HTML, manpage and Markdown so far.

> I agree, "release early, release often"!

So true. I've got stuck with several software projects on my own not being "perfect" enough for a release. Its fatal.

**Comment by farvardin** [comment]
do as you wish. The problem is it's quite difficult to work with fgallaire, and personally I don't want to collaborate any longer with him. I hoped he would loose interest in txt2tags' development, but unfortunately it's not the case :D

**Comment by jendrikseipp** [comment]
I agree with @farvardin. 

Python 2.7 is EOL in seven months, so txt2tags needs to be ported to Python 3.

It seems @fgallaire is against porting to Python 3 (judging by his comment and earlier remarks in other threads). Therefore, I propose to let him maintain txt2tagslite as he likes and let anybody else make changes to the single-file txt2tags implementation.

**Comment by fgallaire** [comment]
@farvardin not sure it's really fair as I'm the only one working on and paying for this project (bug fix, new features, GitHub migration, Netlify migration, domain name)
@jendrikseipp I'm for Python 3 porting (as I said it's the way to go). Do you really think working on a 11k LOC file is a good thing ?
@phorward I don't find your email ? mail me.

**Comment by dingpengyu** [comment]
What is the current state of pr?
thanks

**Comment by farvardin** [comment]
@dingpengyu I'm sorry I suppose the current development of txt2tags is stalled because of internal conflicts in the staff, so the best is probably to create a fork.

**Comment by farvardin** [comment]
@phorward I've worked more with your port of the latest txt2tags (development) version, and it suits me very well!

I've seen you've updated your repository with the new python3 version "from scratch" (from the last 2.6 release, actually), so I've kept the other version on my own repository: https://github.com/farvardin/textallion/tree/master/contrib/txt2tags which I'm using for my project. (I need the template features and a few other one, so your previous version is better for my usage)

**Comment by phorward** [comment]
Hi @farvardin, oh quite cool! I think its useful to put some features over to the new repo. I've also re-uploaded it as a new, unforked repo to https://github.com/phorward/txt2tags-legacy now.

Mostly I'm using the old 2.6 version for my C software docs, but I'm very interested into the markdown support that's only available in 2.7, but not in 3.0. Hopefully @jendrikseipp will add markdown support also soon, I'm doing pull requests as soon as I have some time for it.

**Comment by dingpengyu** [comment]
hi
Is the conflict of txt2tags community members still unresolved?
thanks
cc
@phorward

**Comment by phorward** [comment]
I think it's time to close this for now, due to the new v3 branch in the official repo :+1:

**Comment by aureliojargas** [comment]
@phorward thank you very much for your time and code! :+1:

For those coming from Google searching for the Python 3 version of txt2tags: it's now available as a [package in PyPI](https://pypi.org/project/txt2tags/) (`pip install txt2tags`) and the source code is in the `v3` branch in the txt2tags repo: https://github.com/txt2tags/txt2tags/tree/v3

**Pull request closed without merging**
